---
- hosts: frigg  # all | nyc | hostname | etc
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - import_tasks: tasks/gitea.yml
      when: gitea_enable
