---
- hosts: freyja
  gather_facts: true
  become: true
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      tags: ['pre','apt','update']
    - name: Install some packages
      apt:
        name: '{{ item }}'
        state: present
      loop: '{{ installed_packages }}'
      tags: ['init','pre','apt']
  roles:
    # - role: marcus-grant.mydotfiles
    #   tags: ['dots', 'dotfiles']
    - role: marcus_grant.dotfiles.bash
      tags: [dotfiles,dots,bash]
    # - role: geerlingguy.ntp
    #   tags: ['ntp']

# Non-become play, put all things that should be run as the ssh user here
# - this is opposed to root user
- hosts: freyja
  roles:
    # - role: marcus-grant.mydotfiles
    #   tags: ['dots', 'dotfiles']
    - role: marcus_grant.dotfiles.bash
      tags: [dotfiles,dots,bash]
