---
- hosts: freyja
  gather_facts: true
  become: true
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      tags: ['pre','apt','update']
    - name: Install some packages
      apt:
        name: '{{ item }}'
        state: present
      loop: '{{ installed_packages }}'
      tags: ['init','pre','apt']
    - name: Install some pip packages
      pip:
        name: '{{ item }}'
      loop:
        - stormssh
      tags: ['init', 'pre', 'pip']
  roles:
    - role: marcus-grant.mydotfiles
      tags: ['dots', 'dotfiles']
    # - role: geerlingguy.ntp
    #   tags: ['ntp']

- hosts: freyja
  roles:
    - role: marcus-grant.mydotfiles
      tags: ['dots', 'dotfiles']