---
- hosts: frigg
  gather_facts: true
  become: true
  pre_tasks:
    - import_tasks: tasks/firewalld.yml
  roles:
    - role: ./roles/installer
    - role: geerlingguy.ntp
    #   - role: name=roles/qemu
    #     when: qemu_install
    - role: marcus-grant.mydotfiles
      when: >
        ansible_os_family == "Debian" or
        ansible_os_family == "RedHat"
  post_tasks:
    - import_tasks: tasks/docker_post_install.yml
    - import_tasks: tasks/unifi-firewall.yml
    - import_tasks: tasks/unifi.yml

# Do these things only as the ssh user
- hosts: frigg
  gather_facts: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  roles:
    - role: marcus-grant.mydotfiles
