all:
  children:
    homeservers:
      hosts:
        default:
          ansible_host: 127.0.0.1
          ansible_port: 2222 # test
          ansible_user: vagrant
          # TODO: below needs a way to be used on any relative project path
          ansible_ssh_private_key_file: '/home/marcus/Code/devops/ansible/playbooks/mycloud/.vagrant/machines/default/virtualbox/private_key'

      # children:
      #   default:
