all:
  children:
    homeservers:
      hosts:
        default:
          ansible_host: 127.0.0.1
          ansible_port: 2222 # test
          ansible_user: vagrant

      # children:
      #   default:
