---
- hosts: all
  user: root
  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: dist

    # - name: Create main admin user
    #   user:
    #     name: '{{ main_admin_user }}'
    #     password: '{{ ansible_become_password | password_hash("sha512", main_admin_user) }}'
    #     groups: [sudo]
    #     state: present
    #     shell: /bin/bash
    #     createhome: true
    
    # - name: 'Allow "sudo" group to sudo'
    #   lineinfile:
    #     path: /etc/sudoers
    #     state: present
    #     regexp: '^%sudo'
    #     line: '%sudo	ALL=(ALL:ALL) ALL'
    #     validate: '/usr/sbin/visudo -cf %s'
    
    # - name: Install fail2ban
    #   apt:
    #     name: fail2ban
    #     state: latest
    
    - name: Install iptables with apt
      apt:
        name: iptables
        state: latest

    - name: Flush existing firewall rules
      iptables:
        flush: true

    - name: Firewall Rule - accept all loopback traffic
      iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
    
    - name: Firewall Rule - allow established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: 'Firewall Rule - accept SSH traffic on port {{ custom_ssh_port }}'
      iptables:
        chain: INPUT
        destination_port: '{{ custom_ssh_port }}'
        jump: ACCEPT
        protocol: tcp
    
    - name: Firewall Rule - accept port 80/HTTP traffic
      iptables:
        chain: INPUT
        destination_port: 80
        jump: ACCEPT
        protocol: tcp

    - name: Firewall Rule - accept port 443/HTTPS traffic
      iptables:
        chain: INPUT
        destination_port: 443
        jump: ACCEPT
        protocol: tcp

    - name: Firewall Rule - drop any traffic without rule
      iptables:
        chain: INPUT
        jump: DROP

    - name: 'Install "netfilter-persistent" && "iptables-persistent" packages'
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - iptables-persistent
        - netfilter-persistent
      when: ansible_os_family == "Debian"