---
# - hosts: all
#   gather_facts: true
#   become: true
#   roles:
#     - role: marcus-grant.common-packages
#     - role: geerlingguy.ntp
#     - role: geerlingguy.docker
#       when: >
#         ansible_os_family == "Debian" or
#         ansible_os_family == "RedHat"

- hosts: ocean
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  tasks:
    - include_tasks: tasks/ufw-traefik.yml
    - include_tasks: tasks/docker_post_install.yml
      when: docker_install | default(False)
    - include_role:
        name: roles/docker-on-traefik  # TODO: change name
      when: traefik_enabled | default(False)
    - include_role:
        name: roles/nextcloud-on-docker  # TODO: change name
      when: nextcloud_enabled | default(False)
    # - include_tasks: tasks/nextcloud.yml
    #   when: (nextcloud_enabled | default(False))
    #   tags: nextcloud


# These are workstations that double as servers with different handling
# - hosts: workstations
#   gather_facts: true
#   tasks:
#     - name: docker is instaled using pacman
#       pacman:
#         name: docker
#         state: present
