---
- hosts: all
  gather_facts: yes
  roles:
    - role: marcus-grant.common-packages
      become: yes
    - role: marcus-grant.mydotfiles
    - role: marcus-grant.mydotfiles
      allow_duplicates: yes
      become: yes
      remote_user: root

# These will only be done on 'homeservers' group ie metal servers owned
- hosts: homeservers
  gather_facts: yes
  tasks:
    - debug: { msg: 'hello homeservers' }
    # - include_role:
    #     name: geerlingguy.docker
