---
- hosts: all
  gather_facts: yes
  roles:
    - role: marcus-grant.common-packages
      become: yes
    - role: marcus-grant.mydotfiles
    - role: marcus-grant.mydotfiles
      allow_duplicates: yes
      become: yes
      remote_user: root
    - role: geerlingguy.ntp
      become: yes

# These will only be done on 'homeservers' group ie metal servers owned
- hosts: homeservers
  gather_facts: yes
  roles:
    - name: geerlingguy.docker
      become: yes

  tasks:
    - import_tasks: tasks/docker_post_install.yml
      become: yes
    - import_tasks: tasks/portainer.yml
      become: yes
      when: (portainer_enabled | default(False))
      tags: portainer
    # placeholder for traefik, should appear near beginning after portainer
    - import_tasks: tasks/unifi.yml
      become: yes
      when: (unifi_enabled | default(False))
      tags: unifi
    - import_tasks: tasks/nextcloud.yml
      become: yes
      when: (nextcloud_enabled | default(False))
      tags: nextcloud


# These are workstations that double as servers with different handling
# - hosts: workstations
#   gather_facts: yes
#   tasks:
#     - name: docker is instaled using pacman
#       pacman:
#         name: docker
#         state: present
