---
- hosts: all
  gather_facts: yes
  # pre_tasks:
    # - import_tasks: tasks/cli-packages.yml
    # - import_tasks: tasks/gui-packages.yml
  roles:
    - marcus-grant.common-packages
    - marcus-grant.mydotfiles

# These will only be done on 'homeservers' group ie metal servers owned
- hosts: homeservers
  gather_facts: yes
  tasks:
    - debug: { msg: 'hello homeservers' }
    # - include_role:
    #     name: geerlingguy.docker
