---
- hosts: all
  gather_facts: yes
  roles:
    - role: marcus-grant.common-packages
      become: yes
    - role: marcus-grant.mydotfiles
    - role: marcus-grant.mydotfiles
      allow_duplicates: yes
      become: yes
      remote_user: root

# These will only be done on 'homeservers' group ie metal servers owned
- hosts: homeservers
  gather_facts: yes
  roles:
    - role: geerlingguy.docker
      become: yes

# These are workstations that double as servers with different handling
# - hosts: workstations
#   gather_facts: yes
#   tasks:
#     - name: docker is instaled using pacman
#       pacman:
#         name: docker
#         state: present
