---
- hosts: all
  gather_facts: yes
  roles:
    # - role: marcus-grant.common-packages
    #   become: yes
    # - role: marcus-grant.mydotfiles
    # - role: marcus-grant.mydotfiles
    #   allow_duplicates: yes
    #   become: yes
    #   remote_user: root
    # - role: geerlingguy.ntp
    #   become: yes

# These will only be done on 'homeservers' group ie metal servers owned
- hosts: homeservers
  gather_facts: yes
  roles:
    # - name: geerlingguy.pip
    #   become: yes
    - name: geerlingguy.docker
      become: yes

  tasks:
    - import_tasks: tasks/docker_server_env.yml
      become: yes
    - import_tasks: tasks/portainer.yml
      become: yes
      when: (portainer.enabled | default(False))
      tags: portainer
    # placeholder for traefik, should appear near beginning after portainer


# These are workstations that double as servers with different handling
# - hosts: workstations
#   gather_facts: yes
#   tasks:
#     - name: docker is instaled using pacman
#       pacman:
#         name: docker
#         state: present
