---
- hosts: all
  gather_facts: yes
  pre_tasks:
    # - import_tasks: tasks/cli-packages.yml
    # - import_tasks: tasks/gui-packages.yml
  roles:
    - roles/my-common-packages
    - marcus-grant.mydotfiles
