all:
  children:
    homeservers:
      hosts:
        default: # the vagrant testing server
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
        # freyr:
        #   # ansible_hobst: 192.168.1.12
        #   ansible_port: 22
        #   ansible_user: marcus
