---
roles:
  - name: marcus-grant.mydotfiles
    src: https://github.com/marcus-grant/role-mydotfiles
    version: master
  - name: marcus-grant.common-packages
    src: https://github.com/marcus-grant/role-my-common-packages
    version: master
  - name: geerlingguy.ntp
  - name: geerlingguy.docker
  - name: geerlingguy.mysql
  - name: m3nu.ansible_role_borgbackup
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.docker
  - name: community.crypto
  - name: containers.podman
