---
- name: marcus-grant.mydotfiles
  src: https://github.com/marcus-grant/role-mydotfiles
  version: master
- name: marcus-grant.common-packages
  src: https://github.com/marcus-grant/role-my-common-packages
  version: master
- name: geerlingguy.ntp
- name: geerlingguy.docker
# - name: container_image_cleanup
#   src: ikke_t.container_image_cleanup
#   version: master
# - name: podman_container_systemd
#   src: ikke_t.podman_container_systemd
#   version: master
# - name: geerlingguy.pip
