---
- hosts: snori
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  tasks:
    - include_tasks: tasks/docker_post_install.yml

# run for only the ansible user
- hosts: homeservers
  gather_facts: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  tasks:
    - include_role:
        name: marcus-grant.mydotfiles

# - include_role:
#     name: roles/docker-on-traefik
#   when: traefik_enabled | default(False)
# - include_role: name=roles/nextcloud-on-docker
#   when: nextcloud_enabled | default(False)
#
# - hosts: ocean
#   gather_facts: true
#   become: true
#   vars_files:
#     - group_vars/vault.yml
#   handlers:
#     - import_tasks: handlers.yml
#   tasks:
#     # - include_tasks: tasks/ufw-traefik.yml
#     # - include_tasks: tasks/docker_post_install.yml
#     #   when: docker_install | default(False)
#     # - include_role:
#     #     name: roles/docker-on-traefik
#     #   when: traefik_enabled | default(False)
#     - include_role: name=roles/s3fs-mount
#       when: s3fs_mounts is defined and (s3fs_mounts | length > 0)
#     - include_role: name=roles/nextcloud-on-docker
#       when: nextcloud_enabled | default(False)
