---
- hosts: vor
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      tags: ['pre','apt','update']
    - name: Install some packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - python-pip
        - python-docker
        - python3
        - python3-setuptools
        - python3-pip
        - python3-docker
      tags: ['init','pre','apt']
    - name: Install some pip packages
      pip:
        name: '{{ item }}'
      loop:
        - stormssh
      tags: ['init', 'pre', 'pip']
  roles:
    - role: geerlingguy.ntp
      tags: ['ntp']
    - role: hetzner-box
      tags: ['box', 'hbox', 'storage', 'hetzner']
    - role: geerlingguy.mysql
      tags: ['mysql']
    - role: geerlingguy.docker
      tags: ['docker']
    - role: docker-server-traefik-proxy
      tags: ['docker', 'container', 'proxy', 'traefik']