---
- hosts: vor
  gather_facts: true
  become: true
  vars_files:
    - group_vars/vault.yml
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      tags: ['pre','apt','update']
    - name: Install some packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - python-pip
        - python3
        - python3-pip
      tags: ['init','pre','apt']
  roles:
    - { role: geerlingguy.ntp, tags: ['ntp'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    # - role: marcus-grant.mydotfiles
    #   when: >
    #     ansible_os_family == "Debian" or
    #     ansible_os_family == "RedHat"
  # post_tasks:
    # - import_tasks: tasks/docker_post_install.yml
    # - import_tasks: tasks/unifi-firewall.yml
    # - import_tasks: tasks/unifi.yml
    # - import_tasks: tasks/firewalld.yml

# Do these things only as the ssh user
# - hosts: frigg
#   gather_facts: true
  # vars_files:
  #   - group_vars/vault.yml
  # handlers:
  #   - import_tasks: handlers.yml
  # roles:
  #   - role: marcus-grant.mydotfiles
