---
- name: 'docker home directory exists @ {{ docker_home }}'
  # become: true
  file:
    path: "{{ docker_home }}"
    state: directory
    owner: root
    group: docker
    mode: 0770

# TODO: during a refactor, check if this is necessary with geerlinguys role
# TODO: this needs to be handled differently for non debian based OSs
- name: install needed docker management dependencies
  apt: name={{ item }} state=latest update_cache=true
  loop:
    - python-setuptools
    - python-pip
    - python-docker
    - python3-setuptools
    - python3-pip
    - python3-docker
    - virtualenv

- name: 'ensure ansible user is added to docker group'
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: true
    shell: /bin/bash
  when: docker_group_admin_user | default(False)

- name: change docker root/home directory from defaults
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: restart docker if dameon config changed
  become: true
  service:
    name: docker
    state: restarted
  when: docker_config.changed

# Fix bug where system-level ssl_match_hostname module installed @ sys level
# Taken from this stack overflow http://bit.ly/2HCMwXO
# - name: fix debian 10 docker-py dependency bug, uninstall pip2 version
#   pip:
#     name: docker-py
#     state: absent
#     executable: pip2
# # Same for python3
# - name: fix debian 10 docker-py dependency bug, uninstall pip3 version
#   pip:
#     name: docker
#     state: absent
#     executable: pip3


# - name: ensure python (pip) docker-ppy module installed
#   # become: true
#   pip:
#     name: docker-py
#     executable: pip2
# - name: ensure python 3 (pip) docker module installed
#   # become: true
#   pip:
#     name: docker
#     executable: pip3
