---
- name: 'docker home directory exists @ {{ docker_home }}'
  # become: true
  file:
    path: "{{ docker_home }}"
    state: directory
    owner: root
    group: docker
    mode: 0770

# TODO: during a refactor, check if this is necessary with geerlinguys role
# TODO: this needs to be handled differently for non debian based OSs
- name: install needed docker management dependencies
  apt: name={{ item }} state=latest update_cache=true
  loop:
    - python-setuptools
    - python-pip
    - python3-setuptools
    - python3-pip
    - virtualenv

- name: install docker python libs on pip (2)
  pip:
    name: docker
    executable: pip2

- name: install docker python libs on pip3
  pip:
    name: docker
    executable: pip3

- name: 'ensure ansible user is added to docker group'
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: true
    shell: /bin/bash
  when: docker_group_admin_user | default(False)

- name: change docker root/home directory from defaults
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: restart docker if dameon config changed
  become: true
  service:
    name: docker
    state: restarted
  when: docker_config.changed