---
- name: nextcloud docker directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ nextcloud_docker_directory }}'
    - '{{ nextcloud_docker_directory }}/db'
    - '{{ nextcloud_docker_directory }}/app'
    - '{{ nextcloud_host_data_directory }}'

- name: ensure nextcloud host data directory owned by www-data
  file:
    path: '{{ nextcloud_host_data_directory }}'
    owner: '{{ nextcloud_app_data_user }}'
    group: '{{ nextcloud_app_data_user }}'

- name: nextcloud mariadb docker container
  docker_container:
    name: nextcloud-db
    image: mariadb
    pull: true
    volumes:
      - '{{ nextcloud_docker_directory }}/db:/var/lib/mysql:rw'
    env:
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: '{{ nextcloud_db_user }}'
      MYSQL_PASSWORD: '{{ nextcloud_db_user_passwd }}'
      MYSQL_ROOT_PASSWORD: '{{ nextcloud_db_root_passwd }}'
    restart_policy: unless-stopped
    # memory: '{{ nextcloud_db_memory }}'

- name: nextcloud app server docker container
  docker_container:
    name: nextcloud-app
    image: nextcloud:16
    pull: true
    links:
      - 'nextcloud-db:nextcloud-db'
    volumes:
      - '{{ nextcloud_docker_directory }}/app:/var/www/html:rw'
      - '{{ nextcloud_host_data_directory }}:/var/www/html/data:rw'
    ports:
      - '{{ nextcloud_app_port }}:80'
    env:
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: '{{ nextcloud_db_user }}'
      MYSQL_PASSWORD: '{{ nextcloud_db_user_passwd }}'
      NEXTCLOUD_TRUSTED_DOMAINS: '{{ nextcloud_trusted_domains }}'
    restart_policy: unless-stopped
    # memory: '{{ nextcloud_app_memory }}'
    # labels:
    #   traefik.backend: 'nextcloud'
    #   traefik.frontend.rule: 'Host:nextcloud.{{ ansible_nas_domain }}'
    #   traefik.enable: '{{ nextcloud_available_externally }}'
    #   traefik.port: '80'
