---
- name: create unifi docker data directory
  file:
    path: '{{ unifi_docker_directory }}'
    state: directory
    owner: root
    group: docker
    mode: 0770

- name: unifi controller docker container
  docker_container:
    name: unifi
    image: linuxserver/unifi
    pull: yes
    restart_policy: unless-stopped
    volumes:
      - '{{ unifi_docker_directory }}:/config'
    env:
      PGID: '997'
      PUID: '1000'
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '8080:8080'
      - '8081:8081'
      - '8443:8443'
      - '8843:8843'
      - '8880:8880'
      - '6789:6789'