---
- block:

  - name: Create group git
    group:
      name: '{{ git_group }}'
      gid: '{{ git_gid | default(omit) }}'
  
  - name: Create user git
    user:
      name: '{{ git_user }}'
      group: '{{ git_group }}'
      uid: '{{ git_uid | default(omit) }}'
      home: '{{ git_home }}'
      password: '{{ git_user_passwd | password_hash("sha512") }}'
      update_password: on_create
      password_lock: true
      shell: '/bin/bash'
  
  - name: Prepare gitea expected directory structure
    file:
      state: directory
      path: '{{ git_home }}/{{ item.dir }}'
      owner: '{{ git_user }}'
      group: '{{ git_group }}'
      mode: '0750'
    loop:
      - { dir: 'data', enable: true }
      - { dir: 'log', enable: true }
      - { dir: 'indexers', enable: '{{ git_indexer_enable }}' }
    when: item.enable

  when: gitea_enabled | default(false)
  tags: ['git', 'gitea']