---
- block:

  - name: Create group git
    group:
      name: '{{ git_group }}'
      gid: '{{ git_gid | default(omit) }}'
  
  - name: Create user git
    user:
      name: '{{ git_user }}'
      group: '{{ git_group }}'
      uid: '{{ git_uid | default(omit) }}'
      home: '{{ git_home }}'
      password: '{{ git_user_passwd | password_hash("sha512") }}'
      update_password: on_create
      password_lock: true
      shell: '/bin/bash'
  
  - name: Prepare gitea expected directory structure
    file:
      state: directory
      path: '{{ git_home }}/{{ item.dir }}'
      owner: '{{ git_user }}'
      group: '{{ git_group }}'
      mode: '0750'
    loop:
      - { dir: 'data', enable: true }
      - { dir: 'log', enable: true }
      - { dir: 'db', enable: '{{ git_db_container_enable }}' }
      - { dir: 'indexers', enable: '{{ git_indexer_enable }}' }
    when: item.enable
  
  - name: Gitea PostgreSQL database docker container
    community.docker.docker_container:
      name: 'gitea-db'
      state: 'started'
      container_default_behavior: 'compatibility'
      restart_policy: 'unless-stopped'
      image: 'postgres:{{ git_db_image_tag }}'
      network_mode: 'bridge'
      networks:
        - name: '{{ git_docker_network }}'
      ports: # This is only open for the sake of tunneling in with DB GUIs
        - '5432:5432'
      # user: '{{ git_uid | string }}:{{ git_gid | string }}'
      env:
        POSTGRES_USER: '{{ git_user }}'
        POSTGRES_PASSWORD: '{{ git_db_passwd }}'
        POSTGRES_DB: '{{ git_user }}'
        USERMAP_UID: '{{ git_uid | string }}'
        USERMAP_GID: '{{ git_gid | string }}'
      volumes:
        - '{{ git_home }}/db:/var/lib/postgresql/data'
  
  - name: Gitea server docker container
    community.docker.docker_container:
      name: 'gitea'
      state: 'started'
      container_default_behavior: 'compatibility'
      restart_policy: 'unless-stopped'
      image: 'gitea/gitea:{{ git_image_tag }}'
      network_mode: 'bridge'
      networks:
        - name: '{{ git_docker_network }}'
      ports:
        - '{{ git_port_http }}:3000'
        - '{{ git_port_ssh }}:22'
      env:
        USER_UID: '{{ git_uid | string }}'
        USER_GID: '{{ git_gid | string }}'
        DB_TYPE: 'postgres'
        DB_HOST: 'gitea-db:5432'
        DB_NAME: '{{ git_user }}'
        DB_USER: '{{ git_user }}'
        DB_PASSWD: '{{ git_db_passwd }}'
        SSH_DOMAIN: '{{ git_subdomain }}.{{ base_domain }}'
        SSH_PORT: '22'
      volumes:
        - '{{ git_home }}/data:/data'
        - '{{ git_home }}/log:/log'
        - '{{ git_home }}/indexers:/indexers'
        - '/etc/timezone:/etc/timezone:ro'
        - '/etc/localtime:/etc/localtime:ro'
      labels:
        traefik.enable: 'true'
        traefik.http.routers.git.rule: 'Host(`{{ git_subdomain }}.{{ base_domain }}`)'
        traefik.http.routers.git.tls: 'true'
        traefik.http.routers.git.tls.certresolver: 'lets-encrypt'
        traefik.http.services.git.loadbalancer.server.port: '{{ git_port_http }}'
  
  - name: 'Firewall - ACCEPT Gitea SSH traffic port {{ custom_ssh_port }}'
    iptables:
      chain: INPUT
      destination_port: '{{ git_port_ssh }}'
      jump: ACCEPT
      protocol: tcp
    

  when: gitea_enabled | default(false)
  tags: ['git', 'gitea']