---
# tasks file for docker-traefik-proxy
- name: Include traefik setup tasks
  include_tasks: traefik.yml
  when: traefik_setup

- name: Include gitea setup tasks
  include_tasks: gitea.yml
  when: gitea_enabled | default(false)
