# dotfiles root directory, where all seperate dotfiles subdirectories go
dotfiles_local_root_dir: '~/.dots'
dotfiles_git_server_base_url: 'github.com'
dotfiles_git_username: 'marcus-grant'
dotfiles_use_ssh: true
dotfiles:
  bash:
    repo_name: 'dots-bash'
    local_subdir_name: 'bash'
    version: 'master'
    links:
      - { dest: '~/.bashrc', src: '~/.dots/bash/bashrc' }
      - { dest: '~/.profile', src: '~/.dots/bash/profile' }
      - { dest: '~/.bash_profile', src: '~/.dots/bash/bash_profile' }
  vim:
    repo_name: 'dots-vim'
    local_subdir_name: 'vim'
    version: 'master'
    links:
      - { dest: '~/.vim', src: '~/.dots/vim' }
      - { dest: '~/.vimrc', src: '~/.dots/vim/vimrc' }
  neovim:
    repo_name: 'dots-neovim'
    local_subdir_name: 'neovim'
    version: 'master'
    links:
      - { dest: '~/.config/nvim', src: '~/.dots/neovim' }
  tmux:
    repo_name: 'dots-tmux'
    local_subdir_name: 'tmux'
    version: 'master'
    links:
      - { dest: '~/.tmux.conf', src: '~/.dots/tmux/.tmux.conf' }
      - { dest: '~/.tmux.conf.local', src: '~/.dots/tmux/.tmux.conf.local' }