# dotfiles root directory, where all seperate dotfiles subdirectories go
dotfiles_local_root_dir: '~/.dots'
dotfiles_git_server_base_url: 'github.com'
dotfiles_git_username: 'marcus-grant'
dotfiles_use_ssh: true
dotfiles:
  bash:
    repo_name: 'dots-bash'
    local_subdir_name: 'bash'
    version: 'master'
    links:
      - { dest: '~/.bashrc', src: '~/.dots/bash/bashrc' }
      - { dest: '~/.profile', src: '~/.dots/bash/profile' }
      - { dest: '~/.bash_profile', src: '~/.dots/bash/bash_profile' }
  vim:
    repo_name: 'dots-vim'
    local_subdir_name: 'vim'
    version: 'master'
    links:
      - { dest: '~/.vim', src: '~/.dots/vim' }
      - { dest: '~/.vimrc', src: '~/.dots/vim/vimrc' }
  tmux:
    repo_name: 'dots-tmux'
    local_subdir_name: 'tmux'
    version: 'master'
    links:
      - { dest: '~/.tmux.conf', src: '~/.dots/tmux/.tmux.conf' }
      - { dest: '~/.tmux.conf.local', src: '~/.dots/tmux/.tmux.conf.local' }

# ntp role
# ntp_enabled: no # (true) | false don't use on containerized VM (docker/virtbox)
# ntp_timezone: America/New_York # (Etc/UTC) | many others
# ntp role http://bit.ly/2HBSJ67 <- README
ntp_enabled: yes # (true) | false don't use on containerized VM (docker/virtbox)
ntp_timezone: America/New_York # (Etc/UTC) | many others (America/New_York)
ntp_manage_config: yes # (false) | true, whether to manage /etc/ntp.conf
ntp_area: '' # defaults to none (world), check http://bit.ly/2Hyqoh0 for others
ntp_servers: # defaults to below world pool (only works manage config)
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
ntp_restrict: # whitelists access for these hosts, loopback only by default
  - "127.0.0.1"
  - "::1"

# docker install settings geerlingguy.docker github link: http://bit.ly/2HwZPZG
docker_install: yes
docker_edition: 'ce' # ce or ee
docker_package_state: latest # present, absent, or latest
docker_service_state: started # (started) | stopped *
docker_service_enabled: yes # (yes/true) | no/false *
docker_restart_handler_state: restarted # what to do with service after role
docker_install_compose: yes # (true) | false
# docker_compose_version: "1.22.0" defaults to latest, just leave blank for now
docker_compose_path: /usr/local/bin/docker-compose # path to compose bin