---
### General
# ansible_python_interpreter: auto
ansible_python_interpreter: /usr/bin/python3
# admin_user: '{{ vault_admin_user }}'
admin_group: wheel
timezone: Europe/Stockholm

### Firewalld
firewalld_default_zone: internal
network_default_interface: eno1
cockpit_enable: true

### QEMU
qemu_install: true
qemu_gui_enable: true
qemu_images_location: /mnt/vm

### NTP
ntp_enabled: true  # (true) | false don't use on containerized VM (docker/vbox)
ntp_timezone: '{{ time_zone }}'  # (Etc/UTC) | many others
ntp_manage_config: false  # (false) | true, whether to manage /etc/ntp.conf
ntp_area: 'se'  # defaults to none (world), check http://bit.ly/2Hyqoh0 for others
# ntp_servers:  # defaults to below world pool (only works manage config)
#   - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#   - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#   - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#   - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
ntp_restrict:  # whitelists access for these hosts, loopback only by default
  - "127.0.0.1"
  - "::1"

### Package Installs
installed_packages:
  - python3
  - python3-setuptools
  - python3-pip
  - python3-docker
  - git
  - vim
  - tmux
  - fd-find
  - fzf
  - tree
  - ncdu
  - bpytop
  - libvirt-daemon
  - cryptsetup
  - udisks2-lvm2
  - cockpit-storaged
  - cockpit-machines

### General Docker Settings
# Use this to enable or disable admin user access, forcing sudo & root
docker_group_admin_user: false  # disable docker group access for admin
docker_edition: 'ce'  # ce or ee
# docker_home: /mnt/docker
docker_storage_driver: overlay2
docker_package_state: latest  # present, absent, or latest
docker_service_state: started  # (started) | stopped *
docker_service_enabled: true  # (yes/true) | no/false *
docker_restart_handler_state: restarted  # what to do with service after role
docker_install_compose: true  # (true) | false
docker_compose_path: /usr/local/bin/docker-compose  # path to compose bin

### Dotfiles
dotfiles_local_root_dir: '~/.dots'
dotfiles_git_server_base_url: 'github.com'
dotfiles_git_username: 'marcus-grant'
dotfiles_use_ssh: true
dotfiles:
  bash:
    repo_name: 'dots-bash'
    local_subdir_name: 'bash'
    version: 'main'
    links:
      - {dest: '~/.bashrc', src: '~/.dots/bash/rc.bash'}
      - {dest: '~/.bash_profile', src: '~/.dots/bash/profile.bash'}
  vim:
    repo_name: 'dots-vim'
    local_subdir_name: 'vim'
    version: 'main'
    links:
      - {dest: '~/.vim', src: '~/.dots/vim'}
      - {dest: '~/.vimrc', src: '~/.dots/vim/vimrc'}
  tmux:
    repo_name: 'dots-tmux'
    local_subdir_name: 'tmux'
    version: 'main'
    links:
      - {dest: '~/.tmux', src: '~/.dots/tmux'}
      - {dest: '~/.tmux.conf', src: '~/.dots/tmux/.tmux.conf'}
