---
# tasks file for docker-traefik-proxy
- name: >
    'Set Docker net {{ docker_socket_proxy_network }} for proxied containers'
  community.docker.docker_network:
    name: '{{ docker_socket_proxy_network }}'

- name: Docker Socket Proxy Container
  community.docker.docker_container:
    name: dock-sock-prox
    state: started
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    image: '{{ docker_socket_proxy_image }}'
    network_mode: '{{ docker_socket_proxy_network }}'
    # networks:
    #   - name: '{{ docker_socket_proxy_network }}'
    ports:
      - '{{ docker_socket_proxy_port }}:2375'
    volumes:
      - '{{ docker_socket_mapped_path }}:/var/run/docker.sock'
  register: varDockSockProx

- name: Restart docker container dock-sock-prox when its task changes it
  community.docker.docker_container:
    name: dock-sock-prox
    container_default_behavior: compatibility
    restart: true
  when: varDockSockProx.changed

- name: Create traefik's docker volume
  community.docker.docker_volume:
    name: traefik

- name: Send templated traefik.toml & traefik_dynamic.toml config files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/var/lib/docker/volumes/traefik/_data/{{ item }}'
    owner: root
    group: docker
    mode: '0600'
  loop: ['traefik.toml', 'traefik_dynamic.toml']