---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: debian/bullseye64
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: ansible
