---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: debian/buster64
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
